SELECT t_c.DATABASE_NAME
      , t_c.ENTRY_TYPE_NAME BACKUP_TYPE
      , t_c.STATE_NAME BACKUP_STATUS
      , SECONDS_BETWEEN(SYS_START_TIME,SYS_END_TIME) BACKUP_TIME_S
      , FLOOR(t_cf.BACKUP_SIZE_MB) BACKUP_SIZE_MB
      , SECONDS_BETWEEN(SYS_START_TIME,CURRENT_TIMESTAMP)/3600 TIME_FROM_LAST_H
from "SYS_DATABASES"."M_BACKUP_CATALOG" t_c
left join ( select BACKUP_ID, IFNULL(sum(BACKUP_SIZE/1024/1024),0) BACKUP_SIZE_MB
      from "SYS_DATABASES"."M_BACKUP_CATALOG_FILES"
      where SOURCE_TYPE_NAME <> 'catalog'
      group by BACKUP_ID ) t_cf
on t_cf.BACKUP_ID = t_c.BACKUP_ID
where (t_c.DATABASE_NAME, t_c.ENTRY_TYPE_NAME, t_c.SYS_START_TIME) in
      ( SELECT t_c.DATABASE_NAME, t_c.ENTRY_TYPE_NAME, max(t_c.SYS_START_TIME)
      from "SYS_DATABASES"."M_BACKUP_CATALOG" t_c
      left join "SYS_DATABASES"."M_BACKUP_CATALOG_FILES" t_cf
      on t_c.BACKUP_ID = t_cf.BACKUP_ID
      where t_cf.SOURCE_TYPE_NAME <> 'catalog'
      group by t_c.DATABASE_NAME, t_c.ENTRY_TYPE_NAME )
order by t_c.DATABASE_NAME, t_c.ENTRY_TYPE_NAME desc
